package es.ucm.fdi.is1.apuestas.web;

import java.util.Map;

/**
 * Colores de cada club para dibujar su escudo cuando no hay imagen: {fondo, borde}.
 * Los equipos que no aparecen reciben un color calculado a partir del nombre.
 */
final class Colores {

    static final Map<String, String[]> CLUBES = Map.ofEntries(
            // LaLiga
            Map.entry("Real Madrid", new String[] {"#ffffff", "#febe10"}),
            Map.entry("FC Barcelona", new String[] {"#a50044", "#004d98"}),
            Map.entry("Atlético de Madrid", new String[] {"#cb3524", "#272e61"}),
            Map.entry("Villarreal CF", new String[] {"#ffe667", "#005187"}),
            Map.entry("Athletic Club", new String[] {"#ee2523", "#ffffff"}),
            Map.entry("Real Sociedad", new String[] {"#0067b1", "#ffffff"}),
            Map.entry("Real Betis", new String[] {"#00954c", "#ffffff"}),
            Map.entry("Celta de Vigo", new String[] {"#8ac3ee", "#e5254e"}),
            Map.entry("Valencia CF", new String[] {"#ffffff", "#ee3524"}),
            Map.entry("Sevilla FC", new String[] {"#ffffff", "#d81920"}),
            Map.entry("CA Osasuna", new String[] {"#d91a21", "#0a346f"}),
            Map.entry("Rayo Vallecano", new String[] {"#ffffff", "#e53027"}),
            Map.entry("RCD Espanyol", new String[] {"#007fc8", "#ffffff"}),
            Map.entry("Getafe CF", new String[] {"#005999", "#ffffff"}),
            Map.entry("Deportivo Alavés", new String[] {"#0761af", "#ffffff"}),
            Map.entry("Elche CF", new String[] {"#ffffff", "#05642c"}),
            Map.entry("RC Deportivo", new String[] {"#1d4fa3", "#ffffff"}),
            Map.entry("Levante UD", new String[] {"#004d98", "#a50044"}),
            Map.entry("Málaga CF", new String[] {"#6cace4", "#ffffff"}),
            Map.entry("Racing de Santander", new String[] {"#ffffff", "#00843d"}),
            // Champions League
            Map.entry("Bayern de Múnich", new String[] {"#dc052d", "#0066b2"}),
            Map.entry("Paris Saint-Germain", new String[] {"#004170", "#da291c"}),
            Map.entry("Arsenal", new String[] {"#ef0107", "#ffffff"}),
            Map.entry("Manchester City", new String[] {"#6cabdd", "#1c2c5b"}),
            Map.entry("Liverpool", new String[] {"#c8102e", "#00b2a9"}),
            Map.entry("Inter de Milán", new String[] {"#0068a8", "#000000"}),
            Map.entry("Napoli", new String[] {"#12a0d7", "#ffffff"}),
            Map.entry("Borussia Dortmund", new String[] {"#fde100", "#000000"}),
            Map.entry("Aston Villa", new String[] {"#670e36", "#95bfe5"}),
            Map.entry("Manchester United", new String[] {"#da291c", "#fbe122"}),
            Map.entry("RB Leipzig", new String[] {"#ffffff", "#dd0741"}),
            Map.entry("Sporting CP", new String[] {"#008057", "#ffffff"}),
            Map.entry("FC Porto", new String[] {"#003893", "#ffffff"}),
            Map.entry("AS Roma", new String[] {"#8e1f2f", "#f0bc42"}),
            Map.entry("PSV Eindhoven", new String[] {"#ed1c24", "#ffffff"}),
            Map.entry("Galatasaray", new String[] {"#a90432", "#fdb912"}),
            Map.entry("VfB Stuttgart", new String[] {"#ffffff", "#e32219"}),
            Map.entry("LOSC Lille", new String[] {"#e01e13", "#20325f"}),
            Map.entry("Feyenoord", new String[] {"#e40613", "#ffffff"}),
            Map.entry("Como", new String[] {"#1a4d9e", "#ffffff"}),
            Map.entry("Fenerbahçe", new String[] {"#163962", "#ffed00"}),
            Map.entry("RC Lens", new String[] {"#ec1c24", "#ffe500"}),
            Map.entry("Club Brujas", new String[] {"#0068b3", "#000000"}),
            Map.entry("Shakhtar Donetsk", new String[] {"#f26522", "#000000"}),
            Map.entry("Bodø/Glimt", new String[] {"#ffd400", "#000000"}),
            Map.entry("Slavia Praga", new String[] {"#ffffff", "#e30613"}),
            Map.entry("AEK Atenas", new String[] {"#ffd300", "#000000"}),
            Map.entry("Slovan Bratislava", new String[] {"#64b5e9", "#ffffff"}),
            Map.entry("LASK", new String[] {"#000000", "#ffffff"}),
            Map.entry("Viking FK", new String[] {"#002f6c", "#ffffff"}),
            Map.entry("Sabah FK", new String[] {"#0a2240", "#d4af37"}),
            // Baloncesto
            Map.entry("Real Madrid Baloncesto", new String[] {"#ffffff", "#5a2d81"}),
            Map.entry("Barça Basket", new String[] {"#a50044", "#004d98"}),
            Map.entry("Unicaja", new String[] {"#00843d", "#7b2d8b"}),
            Map.entry("Valencia Basket", new String[] {"#f37021", "#000000"}),
            Map.entry("Baskonia", new String[] {"#0e3a73", "#c8102e"}),
            Map.entry("Gran Canaria", new String[] {"#ffd200", "#0053a0"}),
            Map.entry("Joventut Badalona", new String[] {"#00843d", "#000000"}),
            Map.entry("UCAM Murcia", new String[] {"#c8102e", "#ffffff"}),
            Map.entry("Olympiacos", new String[] {"#e30613", "#ffffff"}),
            Map.entry("Panathinaikos", new String[] {"#007a3d", "#ffffff"}),
            Map.entry("Fenerbahçe Beko", new String[] {"#163962", "#ffed00"}),
            Map.entry("Zalgiris Kaunas", new String[] {"#006a44", "#ffffff"}),
            Map.entry("Los Angeles Lakers", new String[] {"#552583", "#fdb927"}),
            Map.entry("Boston Celtics", new String[] {"#007a33", "#ffffff"}),
            Map.entry("Golden State Warriors", new String[] {"#1d428a", "#ffc72c"}),
            Map.entry("Denver Nuggets", new String[] {"#0e2240", "#fec524"}),
            Map.entry("Oklahoma City Thunder", new String[] {"#007ac1", "#ef3b24"}),
            Map.entry("New York Knicks", new String[] {"#006bb6", "#f58426"}),
            Map.entry("San Antonio Spurs", new String[] {"#000000", "#c4ced4"}),
            Map.entry("Dallas Mavericks", new String[] {"#00538c", "#b8c4ca"}),
            // Tenis, Fórmula 1 y MotoGP (color del país o del equipo)
            Map.entry("Carlos Alcaraz", new String[] {"#c60b1e", "#ffc400"}),
            Map.entry("Alejandro Davidovich", new String[] {"#c60b1e", "#ffc400"}),
            Map.entry("Jannik Sinner", new String[] {"#009246", "#ce2b37"}),
            Map.entry("Novak Djokovic", new String[] {"#0c4076", "#c6363c"}),
            Map.entry("Alexander Zverev", new String[] {"#000000", "#ffce00"}),
            Map.entry("Taylor Fritz", new String[] {"#3c3b6e", "#b22234"}),
            Map.entry("Jack Draper", new String[] {"#012169", "#c8102e"}),
            Map.entry("Holger Rune", new String[] {"#c8102e", "#ffffff"}),
            Map.entry("Max Verstappen", new String[] {"#1e41ff", "#ffd700"}),
            Map.entry("Lance Stroll", new String[] {"#006f62", "#cedc00"}),
            Map.entry("Fernando Alonso", new String[] {"#006f62", "#cedc00"}),
            Map.entry("Carlos Sainz", new String[] {"#005aff", "#ffffff"}),
            Map.entry("Charles Leclerc", new String[] {"#dc0000", "#fff200"}),
            Map.entry("Lewis Hamilton", new String[] {"#dc0000", "#fff200"}),
            Map.entry("Lando Norris", new String[] {"#ff8000", "#000000"}),
            Map.entry("Oscar Piastri", new String[] {"#ff8000", "#000000"}),
            Map.entry("George Russell", new String[] {"#00d2be", "#000000"}),
            Map.entry("Marc Márquez", new String[] {"#cc0000", "#000000"}),
            Map.entry("Francesco Bagnaia", new String[] {"#cc0000", "#000000"}),
            Map.entry("Álex Márquez", new String[] {"#1d3c6e", "#ffffff"}),
            Map.entry("Jorge Martín", new String[] {"#008c45", "#000000"}),
            Map.entry("Pedro Acosta", new String[] {"#ff6600", "#000000"}),
            Map.entry("Marco Bezzecchi", new String[] {"#008c45", "#000000"}));

    private Colores() {
    }
}
